import { useState } from 'react';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const [mainContent, setMainContent] = useState('');
  const [topBarContent, setTopBarContent] = useState(''); // Now using text for the top bar
  const [permanentContent, setPermanentContent] = useState('');

  const handleMouseEnter = (text: string, mainContentText: string) => {
    if (!permanentContent) {
      setMainContent(mainContentText);
      setTopBarContent(text); // Use text directly
    }
  };

  const handleClick = (text: string, mainContentText: string) => {
    setPermanentContent(mainContentText);
    setMainContent(mainContentText);
    setTopBarContent(text); // Make text change permanent on click
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        
     <div className="card">
  <h3 className="cardTitle">ALCHEMISTRESSES:</h3>
  <p className="cardSubtitle">A Moloch LP Cooperative focused on alAsset Liquidity.</p>
</div>


        <div className={styles.topBar}>
          {topBarContent || '<3 '}
        </div>

        <div className={styles.contentArea}>
          <div className={styles.menu}>
            <button
              className={styles.card}
              onMouseEnter={() => handleMouseEnter('mint()', 'mint this bish')}
              onClick={() => handleClick('mint()', 'mint this bish')}>
              <span className={styles.h4}>mint()</span>
            </button>

            <button
              className={styles.card}
              onMouseEnter={() => handleMouseEnter('comm()', 'comm this bish')}
              onClick={() => handleClick('comm()', 'comm this bish')}>
              <span className={styles.h4}>mintComm()</span>
            </button>

            <button
              className={styles.card}
              onMouseEnter={() => handleMouseEnter('marketplace()', 'shop these memberships')}
              onClick={() => handleClick('marketplace()', 'shop these memberships')}>
              <span className={styles.h4}>marketplace()</span>
            </button>

            <button
              className={styles.card}
              onMouseEnter={() => handleMouseEnter('withdraw()', 'withdraw this bish')}
              onClick={() => handleClick('withdraw()', 'withdraw this bish')}>
              <span className={styles.h4}>withdraw()</span>
            </button>

          </div>
          <div className={styles.mainContent}>
            <p>{mainContent}</p>
          </div>
        </div>
      </main>
        
         <footer className={styles.footer}>
        <span>Made with ❤️ by your frens at 🌈</span>
      <div className={styles.socialIcons}>
      <a href="https://twitter.com/rootdraws" target="_blank" rel="noopener noreferrer">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
          <path d="M389.2 48h70.6L305.6 224.2 487 464H345L233.7 318.6 106.5 464H35.8L200.7 275.5 26.8 48H172.4L272.9 180.9 389.2 48zM364.4 421.8h39.1L151.1 88h-42L364.4 421.8z"/>
        </svg>
        </a>
    </div>
    </footer>
    </div>
  );
};

export default Home;
