import { useState } from 'react';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const [mainContent, setMainContent] = useState('');
  const [topBarContent, setTopBarContent] = useState(''); // Now using text for the top bar
  const [permanentContent, setPermanentContent] = useState('');

  const handleMouseEnter = (text: string, mainContentText: string) => {
    if (!permanentContent) {
      setMainContent(mainContentText);
      setTopBarContent(text); // Use text directly
    }
  };

  const handleClick = (text: string, mainContentText: string) => {
    setPermanentContent(mainContentText);
    setMainContent(mainContentText);
    setTopBarContent(text); // Make text change permanent on click
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/favicon.ico" rel="icon" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <div className={styles.topBar}>
          {topBarContent || '<3 '}
        </div>

        <div className={styles.contentArea}>
          <div className={styles.menu}>
            <button
              className={styles.card}
              onMouseEnter={() => handleMouseEnter('mint()', 'mint this bish')}
              onClick={() => handleClick('mint()', 'mint this bish')}>
              <span className={styles.h4}>mint()</span>
            </button>

            <button
              className={styles.card}
              onMouseEnter={() => handleMouseEnter('comm()', 'comm this bish')}
              onClick={() => handleClick('comm()', 'comm this bish')}>
              <span className={styles.h4}>mintComm()</span>
            </button>

            <button
              className={styles.card}
              onMouseEnter={() => handleMouseEnter('marketplace()', 'shop these memberships')}
              onClick={() => handleClick('marketplace()', 'shop these memberships')}>
              <span className={styles.h4}>marketplace()</span>
            </button>

            <button
              className={styles.card}
              onMouseEnter={() => handleMouseEnter('withdraw()', 'withdraw this bish')}
              onClick={() => handleClick('withdraw()', 'withdraw this bish')}>
              <span className={styles.h4}>withdraw()</span>
            </button>

          </div>
          <div className={styles.mainContent}>
            <p>{mainContent}</p>
          </div>
        </div>
      </main>

         <footer className={styles.footer}>
        <span>Made with ❤️ by your frens at 🌈</span>
        <div className={styles.socialIcons}>
          <a href="https://twitter.com" target="_blank" rel="noopener noreferrer"><i className="fab fa-twitter"></i></a>
        </div>
      </footer>

    </div>
  );
};

export default Home;
